export default class NurseShiftSummary {
    constructor(

        public syskey: string,
        public autokey: number,
        public createddate: string,
        public modifieddate: string,
        public userid: string,
        public username: string,
        public RecordStatus: number,
        public SyncStatus: number,
        public SyncBatch: number,
        public usersyskey: number,
        public parentid: number,
        public eMRType: string,
        public refNo: string,
        public rgsNo: number,
        public pId: number,
        public hsId: number,
        public doctorId: string,
        public patientdate: string,
        public daynight: number,
        public t1: string,
        public t2: string,
        public t3: string,
        public t4: string,
        public t5: string,
        public t6: string,
        public t7: string,
        public t8: string,
        public t9: string,
        public t10: string,
        public n1: number,
        public n2: number,
        public n3: number,
        public n4: number,
        public n5: number,
        public n6: number,
        public n7: number,
        public n9: number,
        public n10: number,
        public remark1: string,
        public remark2: string,
    ) { }
}
